hw_10/hw_10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', include('quotes.urls')),
    path('home/', include('quotes.urls')),
]

hw_10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', include('quotes.urls')),
    path('home/', include('quotes.urls')),
    path('create/', include('users.urls'))
]

hw_10/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.exit, name='exit'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login')
]

quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>', views.main, name="root_paginate"),
    path('home/', views.home_view, name='home'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.exit, name='exit'),
    path('login/', views.login, name='login'),
    path('reset-password/', views.reset_password_view, name='reset_password'),

]

quotes/models.py
from django.db import models



class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    
    
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.

hw_10/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'password1',]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'password1',]
        
        
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


from django import forms

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'bio']

hw_10/quotes/views.py
from django.shortcuts import render
from .utils import get_mongodb
from django.core.paginator import Paginator

def main(request):
    db = get_mongodb()
    quotes = list(db.quotes.find())
    per_page = 10
    page = request.GET.get('page', 1)
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def home_view(request):
    return render(request, 'quotes/home.html')

hw_10/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .forms import LoginForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home/')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

def home_view(request):
    return render(request, 'users/home.html')

def exit(request):
    return render(request, 'users/home.html')

quotes/views.py
from django.shortcuts import render
from .utils import get_mongodb
from django.core.paginator import Paginator

def main(request):
    db = get_mongodb()
    quotes = list(db.quotes.find())
    per_page = 10
    page = request.GET.get('page', 1)
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def home_view(request):
    return render(request, 'quotes/home.html')

users/views.py
from django.shortcuts import render, redirect
from .forms import AuthorForm
from .forms import RegisterForm
from .forms import LoginForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home/')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

def create_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home/')
    else:
        form = AuthorForm()
    return render(request, 'users/create.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

def home_view(request):
    return render(request, 'users/home.html')

def exit(request):
    return render(request, 'users/home.html')


from django.shortcuts import render

def reset_password_view(request):
    return render(request, 'quotes/reset_password.html')

hw_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "quotes/style.css" %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 md-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/register" class="btn btn-primary">Register</a>
                    <a href="/login" class="btn btn-primary">Login</a>
                </p>
            </div>
        </div>
    
        {% block content %}{% endblock %}

    </div>
</body>
</html>

hw_10/quotes/templates/quotes/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "quotes/style.css" %}">
    <title>Home</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 md-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/" class="btn btn-primary">Exit</a>
                </p>
                <p>
                    <section class="author-form">
                        <h2>Додати нового автора</h2>
                    
                    <form action="submit-author.php" method="post">
                      <div class="form-group">
                        <label for="name">Ім'я:</label>
                        <input type="text" id="name" name="name" required>
                      </div>
                      
                      <div class="form-group">
                        <label for="bio">Біографія:</label>
                        <textarea id="bio" name="bio" rows="5" required></textarea>
                      </div>                  
                      <button type="submit">Додати автора</button>
                    </form>
                  </section>
                    </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world"> 
                    
                    <a class="tag" href="/tag/change/page/1/">change</a>
                    
                    <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
                    
                    <a class="tag" href="/tag/thinking/page/1/">thinking</a>
                    
                    <a class="tag" href="/tag/world/page/1/">world</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
                <span>by <small class="author" itemprop="author">J.K. Rowling</small>
                <a href="/author/J-K-Rowling">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="abilities,choices"> 
                    
                    <a class="tag" href="/tag/abilities/page/1/">abilities</a>
                    
                    <a class="tag" href="/tag/choices/page/1/">choices</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="inspirational,life,live,miracle,miracles"> 
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                    <a class="tag" href="/tag/life/page/1/">life</a>
                    
                    <a class="tag" href="/tag/live/page/1/">live</a>
                    
                    <a class="tag" href="/tag/miracle/page/1/">miracle</a>
                    
                    <a class="tag" href="/tag/miracles/page/1/">miracles</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
                <span>by <small class="author" itemprop="author">Jane Austen</small>
                <a href="/author/Jane-Austen">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="aliteracy,books,classic,humor"> 
                    
                    <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
                    
                    <a class="tag" href="/tag/books/page/1/">books</a>
                    
                    <a class="tag" href="/tag/classic/page/1/">classic</a>
                    
                    <a class="tag" href="/tag/humor/page/1/">humor</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
                <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
                <a href="/author/Marilyn-Monroe">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="be-yourself,inspirational"> 
                    
                    <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="adulthood,success,value"> 
                    
                    <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
                    
                    <a class="tag" href="/tag/success/page/1/">success</a>
                    
                    <a class="tag" href="/tag/value/page/1/">value</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
                <span>by <small class="author" itemprop="author">André Gide</small>
                <a href="/author/Andre-Gide">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="life,love"> 
                    
                    <a class="tag" href="/tag/life/page/1/">life</a>
                    
                    <a class="tag" href="/tag/love/page/1/">love</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
                <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
                <a href="/author/Thomas-A-Edison">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="edison,failure,inspirational,paraphrased"> 
                    
                    <a class="tag" href="/tag/edison/page/1/">edison</a>
                    
                    <a class="tag" href="/tag/failure/page/1/">failure</a>
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                    <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
                <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
                <a href="/author/Eleanor-Roosevelt">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="misattributed-eleanor-roosevelt"> 
                    
                    <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
                <span>by <small class="author" itemprop="author">Steve Martin</small>
                <a href="/author/Steve-Martin">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="humor,obvious,simile"> 
                    
                    <a class="tag" href="/tag/humor/page/1/">humor</a>
                    
                    <a class="tag" href="/tag/obvious/page/1/">obvious</a>
                    
                    <a class="tag" href="/tag/simile/page/1/">simile</a>
                    
                </div>
            </div>
        
            <nav>
                <ul class="pager">
                    <li class="previous">
                        <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                            <span aria-hidden="true">←</span> Previous</a>
                    </li>
                    
                    <li class="next">
                        <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span>
                        </a>
                    </li>
                    
                </ul>
            </nav>          
            </div>
        </div>

    </div>
</body>
</html>

quotes/templates/quotes/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "quotes/style.css" %}">
    <title>Home</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 md-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="/" class="btn btn-primary">Exit</a>
                    <a href="create/" class="btn btn-primary">Create authors</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world"> 
                    
                    <a class="tag" href="/tag/change/page/1/">change</a>
                    
                    <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
                    
                    <a class="tag" href="/tag/thinking/page/1/">thinking</a>
                    
                    <a class="tag" href="/tag/world/page/1/">world</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
                <span>by <small class="author" itemprop="author">J.K. Rowling</small>
                <a href="/author/J-K-Rowling">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="abilities,choices"> 
                    
                    <a class="tag" href="/tag/abilities/page/1/">abilities</a>
                    
                    <a class="tag" href="/tag/choices/page/1/">choices</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="inspirational,life,live,miracle,miracles"> 
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                    <a class="tag" href="/tag/life/page/1/">life</a>
                    
                    <a class="tag" href="/tag/live/page/1/">live</a>
                    
                    <a class="tag" href="/tag/miracle/page/1/">miracle</a>
                    
                    <a class="tag" href="/tag/miracles/page/1/">miracles</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
                <span>by <small class="author" itemprop="author">Jane Austen</small>
                <a href="/author/Jane-Austen">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="aliteracy,books,classic,humor"> 
                    
                    <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
                    
                    <a class="tag" href="/tag/books/page/1/">books</a>
                    
                    <a class="tag" href="/tag/classic/page/1/">classic</a>
                    
                    <a class="tag" href="/tag/humor/page/1/">humor</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
                <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
                <a href="/author/Marilyn-Monroe">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="be-yourself,inspirational"> 
                    
                    <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
                <span>by <small class="author" itemprop="author">Albert Einstein</small>
                <a href="/author/Albert-Einstein">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="adulthood,success,value"> 
                    
                    <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
                    
                    <a class="tag" href="/tag/success/page/1/">success</a>
                    
                    <a class="tag" href="/tag/value/page/1/">value</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
                <span>by <small class="author" itemprop="author">André Gide</small>
                <a href="/author/Andre-Gide">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="life,love"> 
                    
                    <a class="tag" href="/tag/life/page/1/">life</a>
                    
                    <a class="tag" href="/tag/love/page/1/">love</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
                <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
                <a href="/author/Thomas-A-Edison">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="edison,failure,inspirational,paraphrased"> 
                    
                    <a class="tag" href="/tag/edison/page/1/">edison</a>
                    
                    <a class="tag" href="/tag/failure/page/1/">failure</a>
                    
                    <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
                    
                    <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
                <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
                <a href="/author/Eleanor-Roosevelt">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="misattributed-eleanor-roosevelt"> 
                    
                    <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
                    
                </div>
            </div>
        
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
                <span>by <small class="author" itemprop="author">Steve Martin</small>
                <a href="/author/Steve-Martin">(about)</a>
                </span>
                <div class="tags">
                    Tags:
                    <meta class="keywords" itemprop="keywords" content="humor,obvious,simile"> 
                    
                    <a class="tag" href="/tag/humor/page/1/">humor</a>
                    
                    <a class="tag" href="/tag/obvious/page/1/">obvious</a>
                    
                    <a class="tag" href="/tag/simile/page/1/">simile</a>
                    
                </div>
            </div>
        
            <nav>
                <ul class="pager">
                    <li class="previous">
                        <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                            <span aria-hidden="true">←</span> Previous</a>
                    </li>
                    
                    <li class="next">
                        <a class="{% if not quotes.has_next %} disabled {% endif %}" 
                            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span>
                        </a>
                    </li>
                    
                </ul>
            </nav>          
            </div>
        </div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>